# _config.yml
title: Sherif Refaat
email: your.email@example.com
description: >-
  Engineer, Leader, Mentor
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - .vscode/
  - .github/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore

sass:
  sass_dir: sass
  style: compressed

# Ensure the assets folder is included in the build
include:
  - assets

twitter_username: yourtwitter
github_username:  yourgithub
linkedin_username: yourlinkedin
