# _config.yml
title: Your Name
email: your.email@example.com
description: >-
  Your professional description
baseurl: ""
url: ""
twitter_username: yourtwitter
github_username:  yourgithub
linkedin_username: yourlinkedin

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - .vscode/
  - .github/
  - Gemfile.lock
  - .gitignore

