# .github/workflows/deploy.yml
name: Deploy Jekyll site

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          
      - run: gem install jekyll bundler
      
      - run: bundle exec jekyll build --destination ./_site
      
      - uses: actions/upload-pages-artifact@v2
      
      - uses: actions/deploy-pages@v2
